blank_issues_enabled: true
contact_links:
    - name: CONTRIBUTING.md
      url: https://github.com/volcano-sh/dashboard/blob/main/CONTRIBUTING.md
      about: Please read the CONTRIBUTING.md guide before opening an issue or PR.
    - name: Slack
      url: https://cloud-native.slack.com/archives/C011GJDQS0N
