apiVersion: v1
kind: Namespace
metadata:
    name: volcano-demo
    labels:
        demo.volcano.sh/sample: "true"
---
apiVersion: v1
kind: Namespace
metadata:
    name: volcano-demo-ops
    labels:
        demo.volcano.sh/sample: "true"
