name: Build Check

on:
    pull_request:
        branches: [main]

jobs:
    build-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run Frontend Build
              run: npm run build -w frontend || (echo "Frontend build failed!" && exit 1)

            - name: Run Backend Build
              run: npm run build -w backend || (echo "Backend build failed!" && exit 1)
